name: Deploy GitHub Pages

# 触发条件：在 push 到 master 分支后
on:
  push:
    branches:
      - master

# 任务
jobs:
  build-and-deploy:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      # 1、生成静态文件
      - name: Build
        run: npm install && npm run build

      # Add this step before deploy to check if files exist
      - name: Check build output
        run: ls -la .vuepress/dist

      # 2、部署到 GitHub Pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.BLOG_TOKEN }}
          repository-name: NewLearner4396/blogs
          branch: gh-pages
          folder: .vuepress/dist
          # action 会将dist文件覆盖到当前分支的根目录，弃用
          #注意这里的 folder 是仓库根目录下的 文件夹，也就是 npm run build 生成静态资源的路径，比如有的人是 `docs/.vuepress/dist`
